## Experiment: 12
## Write a Python program to implementation the Backpropagation Algorithm.


In [9]:
import numpy as np
def sigmoid(x):
  return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
  return sigmoid(x) * (1 - sigmoid(x))

In [10]:
def backpropagation(input_size, hidden_layer_sizes, output_size, num_iterations, X, Y,
learning_rate):
    layer_sizes = [input_size] + hidden_layer_sizes + [output_size]
    weights = [np.random.randn(layer_sizes[i + 1], layer_sizes[i]) for i in
    range(len(layer_sizes) - 1)]
    biases = [np.zeros((layer_sizes[i + 1], 1)) for i in range(len(layer_sizes) - 1)]
    costs = []
    for i in range(num_iterations):
        activations = [X]
        zs = []
    for j in range(len(weights)):
        z = np.dot(weights[j], activations[-1]) + biases[j]
        zs.append(z)
        a = sigmoid(z)
        activations.append(a)
        error = activations[-1] - Y
        cost = (1 / (2 * X.shape[1])) * np.sum(np.square(error))
        costs.append(cost)
        dZ = [activations[-1] - Y]
        dW = []
        db = []
    for j in range(len(weights) - 1, -1, -1):
        dW.insert(0, (1 / X.shape[1]) * np.dot(dZ[0], activations[j - 1].T))
        db.insert(0, (1 / X.shape[1]) * np.sum(dZ[0], axis=1, keepdims=True))
        if j > 0:
            dZ.insert(0, np.dot(weights[j].T, dZ[0]) * sigmoid_derivative(activations[j - 1]))
    for j in range(len(weights)):
        weights[j] -= learning_rate * dW[j]
        biases[j] -= learning_rate * db[j]
    return weights, biases, costs

In [11]:
input_size = 2
hidden_layer_sizes = [2, 2]
output_size = 1
num_iterations = 2000
learning_rate = 0.1

X = np.random.randn(input_size, 1000)
Y = np.logical_xor(X[0, :] > 0, X[1, :] > 0).astype(int).reshape(1, -1)

weights, biases, costs = backpropagation(input_size, hidden_layer_sizes, output_size,
num_iterations, X, Y, learning_rate)

for j in range(len(weights)):
    print(f"Final Weights W{j + 1}:\n{weights[j]}")
    print(f"Final Biases b{j + 1}:\n{biases[j]}")

Final Weights W1:
[[-0.40978712 -2.32150158]
 [-0.13740566  0.52380288]]
Final Biases b1:
[[-0.00132608]
 [-0.0004311 ]]
Final Weights W2:
[[ 0.9257782   0.28017377]
 [-1.0158753  -0.56699097]]
Final Biases b2:
[[-0.00588794]
 [ 0.00080913]]
Final Weights W3:
[[-1.2820016   0.18189231]]
Final Biases b3:
[[0.01996305]]
