## Experiment - 3
## The parity of n given bits is 1 if an odd number of them is equal to 1, otherwise it is 0. Build a network of McCulloch–Pitts units capable of computing the parity function of two, three, and four given bits. Appropriately assume any required information yourself.


# 1. Importing NumPy

In [1]:
import numpy as np

# 2. Defining utility functions

In [2]:
# Function for calculating weight sum

def calc_sum(x, w) :
    sum = 0
    for i in range(x.size) :
        sum = sum + (x[i]*w)

    return sum

# Function for checking parity
def parity(ws) :
    if (ws % 2 == 1) :
        return 1
    else :
        return 0
        

# 3. Generating random binary input vectors of size 2, 3 and 4

In [3]:
# Input vector
x1 = np.random.randint(0, 2, size=(2, 1))
x2 = np.random.randint(0, 2, size=(3, 1))
x3 = np.random.randint(0, 2, size=(4, 1))
print(x1, "\n")
print(x2, "\n")
print(x3, "\n")

# Setting weights
w = np.array([3])

[[1]
 [1]] 

[[0]
 [1]
 [0]] 

[[0]
 [1]
 [0]
 [1]] 



# 4. Checking parity for each input vector

In [4]:
# Calculating sum
ws = []
ws1 = calc_sum(x1, w)
ws.append(ws1)
ws2 = calc_sum(x2, w)
ws.append(ws2)
ws3 = calc_sum(x3, w)
ws.append(ws3)

ws = np.array(ws)
print(ws)
# Checking if Odd parity or not
for s in ws :
    if (parity(s) == 1) :
        print("Odd parity")
    else :
        print("Even parity")

[[6]
 [3]
 [6]]
Even parity
Odd parity
Even parity
